App\Entity\Menus:
    collectionsOperations:
        get: ~
        post_menus:
            method: POST
            path: /menus2
            controller: App\Controller\MenusController

App\Entity\Commande:
    attributes:
        ligneDeCommandes:
            max_depth: 2